export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const SIGN_SUCCESS='SIGN_SUCCESS';

export const UPDATE_SCHOOL='UPDATE_SCHOOL';

export const MYTEACHER_LOADING_START='MYTEACHER_LOADING_START';
export const STORE_MYTEACHERS='STORE_MYTEACHERS';
export const LOADING_MYTEACHER_FAIL='LOADING_MYTEACHER_FAIL';
export const MYSTUDENT_LOADING_START='MYSTUDENT_LOADING_START';
export const STORE_MYSTUDENTS='STORE_MYSTUDENTS';
export const LOADING_MYSTUDENT_FAIL='LOADING_MYSTUDENT_FAIL';

export const TEACHER_UPDATED_START='TAECHER_UPDATED_START';
export const TEACHER_UPDATED='TEACHER_UPDATED';
export const TEACHER_UPDATED_ERROR='TEACHER_UPDATED_ERROR';
export const STUDENT_UPDATED_START='STUDENT_UPDATED_START';
export const STUDENT_UPDATED='STUDENT_UPDATED';
export const STUDENT_UPDATED_ERROR='STUDENT_UPDATED_ERROR';

export const ADD_TEACHER_START='ADD_TEACHER_START';
export const ADD_TEACHER_SUCCESS='ADD_TEACHER_SUCCESS';
export const ADD_TEACHER_ERROR='ADD_TEACHER_ERROR';
export const ADD_STUDENT_START='ADD_STUDENT_START';
export const ADD_STUDENT_SUCCESS='ADD_STUDENT_SUCCESS';
export const ADD_STUDENT_ERROR='ADD_STUDENT_ERROR';

export const TEACHER_DELETE_START='TEACHER_DELETE_START';
export const TEACHER_DELETE_SUCCESS='TEACHER_DELETE_SUCCESS';
export const TEACHER_DELET_FAIL='TEACHER_DELET_FAIL';
export const STUDENT_DELETE_START='STUDENT_DELETE_START';
export const STUDENT_DELETE_SUCCESS='STUDENT_DELETE_SUCCESS';
export const STUDENT_DELETE_FAIL='STUDENT_DELETE_FAIL';

export const STORE_TASKS_TEACHER='STORE_TASKS_TEACHER';
export const ADD_TASK_SUCCESS='ADD_TASK_SUCCESS';

export const FEE_LOADING_START='FEE_LOADING_START';
export const FEE_LOADING_SUCCESS='FEE_LOADING_SUCCESS';
export const FEE_LOADING_ERROR='FEE_LOADING_ERROR';
export const FEE_DELETE_START='FEE_DELETE_START';
export const FEE_DELETE_SUCCESS='FEE_DELETE_SUCCESS';
export const FEE_DELETE_ERROR='FEE_DELETE_ERROR';
export const FEE_ADD_START='FEE_ADD_START';
export const FEE_ADD_SUCCESS='FEE_ADD_SUCCESS';
export const FEE_ADD_ERROR='FEE_ADD_ERROR';

export const GETTING_FEES_START='GETTING_FEES_START';
export const GETTING_FEES_SUCCESS='GETTING_FEES_SUCCESS';
export const GETTING_FEES_ERROR='GETTING_FEES_ERROR';
export const UPDATING_FEES_START='UPDATING_FEES_START';
export const UPDATING_FEES_SUCCESS='UPDATING_FEES_SUCCESS';
export const UPDATING_FEES_ERROR='UPDATING_FEES_ERROR';

export const GETTING_ALL_BOOK_START='GETTING_ALL_BOOK_START';
export const GETTING_ALL_BOOK_SUCCESS='GETTING_ALL_BOOK_SUCCESS';
export const GETTING_ALL_BOOK_ERROR='GETTING_ALL_BOOK_ERROR';
export const ISSUE_BOOK_START='ISSUE_BOOK_START';
export const ISSUE_BOOK_SUCCESS='ISSUE_BOOK_SUCCESS';
export const ISSUE_BOOK_ERROR='ISSUE_BOOK_ERROR';
export const UPDATE_BOOK_START='UPDATE_BOOK_START';
export const UPDATE_BOOK_SUCCESS='UPDATE_BOOK_SUCCESS';
export const UPDATE_BOOK_FAIL='UPDATE_BOOK_FAIL';


export const STUDENT_PROPERTY_LOADING_START='STUDENT_PROPERTY_LOADING_START';
export const STUDENT_STORE_FEES='STUDENT_STORE_FEES';
export const STUDENT_STORE_BOOKS='STUDENT_STORE_BOOKS';
export const STUDENT_STIRE_TASKS='STUDENT_STIRE_TASKS';
export const STUDENT_PROPERTY_LOADING_ERROR='STUDENT_PROPERTY_LOADING_ERROR';